### PR TITLE
Release 5.0

### PR DESCRIPTION
**Pull request by jonhoo**
Now that we have a bunch of new changes and improvements, I suggest we cut a new release and publish to crates.io. I also think it's high time you're listed as an author @marshallpierce! I can add you to the crates.io as a crate owner too if you're interested?

/cc @danburkert

### CODE REVIEW

**Comment by marshallpierce** [comment]
Hooray, I've graduated ;) I'm happy to be a crates.io owner too.

I do have one vaguely breaking change waiting in the wings about percentile calculations (see enormous chat log in gitter hdrhistogram room). I don't have the branch ready immediately, though, so it would mean waiting a few days for me to finish assembling it. If there isn't a pressing need for a release immediately, I'd like to include that change in the next major release train. Thoughts?

**Comment by jonhoo** [comment]
Sure, then let's wait for that. I was mostly thinking of @danburkert who seems like he might want his new changes and sync with the latest `hdrsample` (which is beyond 4.0). But I'm okay with waiting.

**Comment by danburkert** [comment]
I'm not in a hurry :)

**Comment by marshallpierce** [comment]
OK, great. I'm out of town this weekend but I should be able to get it PRable by Tuesday or so.

**Comment by jonhoo** [comment]
Merged and published!

**Pull request merged**
